# Generated by Django 5.2.3 on 2025-06-20 01:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "data_nascimento",
                    models.DateField(blank=True, null=True, verbose_name="Nascimento"),
                ),
                (
                    "data_obito",
                    models.DateField(blank=True, null=True, verbose_name="Falecimento"),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            (1, "Romance"),
                            (2, "Conto"),
                            (3, "Novela"),
                            (4, "Ensaio"),
                            (5, "Teatro"),
                            (6, "Poema"),
                            (7, "Outro"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Nome do Gênero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gênero",
                "verbose_name_plural": "Gêneros",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do País"
                    ),
                ),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "titulo_original",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Título Original",
                    ),
                ),
                (
                    "ano_publicacao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano de Publicação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Lido", "Lido"),
                            ("Lendo Agora", "Lendo Agora"),
                            ("Quero Ler", "Quero Ler"),
                            ("Abandonado", "Abandonado"),
                        ],
                        default="Quero Ler",
                        max_length=15,
                        verbose_name="Status de Leitura",
                    ),
                ),
                (
                    "avaliacao",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Sua Avaliação",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Início da Leitura"
                    ),
                ),
                (
                    "data_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "arquivo",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Caminho do Arquivo",
                    ),
                ),
                (
                    "capa",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="book_covers/",
                        verbose_name="Capa do Livro",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="livros_do_autor",
                        to="livros.autor",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="livros_do_genero",
                        to="livros.genero",
                        verbose_name="Gênero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
                "ordering": ["titulo"],
            },
        ),
        migrations.AddField(
            model_name="autor",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="autores",
                to="livros.pais",
                verbose_name="País de Origem",
            ),
        ),
    ]
