# Generated by Django 5.2.3 on 2025-06-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genero",
            name="nome",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Nome do Gênero"
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="arquivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="file_livros/arquivos/",
                verbose_name="Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="capa",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="file_livros/capas/",
                verbose_name="Capa do Livro",
            ),
        ),
    ]
