# Generated by Django 5.2.3 on 2025-06-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0002_alter_genero_nome_alter_livro_arquivo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="avaliacao",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="data_fim",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="data_inicio",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="status",
        ),
        migrations.AddField(
            model_name="livro",
            name="lido",
            field=models.BooleanField(default=False, verbose_name="Lido"),
        ),
    ]
